### PR TITLE
Add Python script to convert unit. 

### PR DESCRIPTION
**Pull request by qiguaiderenmen**
TODO: 1, velocity check; 2, pos and vel only correct for j1-5. j6-7 coupling is not considered yet. Also no brake current considered. NOTEs: pos need to subtract mid range; classic CN8 not used, shouldn't be a problem.

### CODE REVIEW

**Comment by pkazanzides** [comment]
It would be better if the generation (-g) did not have to be specified. Couldn't this be output by the data collection software, either as a separate file or as a header line?  In the latter case, would need to specify `skip_header` in `np.genfromtext.` Actually, why is generation necessary? It seems to only be used as a check that an appropriate config file has been loaded (i.e., with or without pot lookup table).

**Comment by qiguaiderenmen** [comment]
Right. It's only used to check if the config and data file agrees. I can also use the number of motors (motor current) and the lookup table existence.

Also we don't need to skip header. I specify name=true, in which numpy uses the first row as header line (like dict).

**Comment by pkazanzides** [comment]
Good.   Could you also update the ReadMe?  The skip_header would only be needed if we added a header of meta-data (i.e., before the column headings).

**Comment by qiguaiderenmen** [comment]
Gotcha. Pls lmk when you decide how to deal with the meta-data.

**Pull request merged**
